[package]
name = "daily_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
chrono = "0.4"
serde_json = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
rfd = "0.15.2"
image = "0.25.5"
notify-rust = "4.11.4"

[build-dependencies]
winresource = "0.1.19"
